name: icon_gen
description: Icon generator
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  calcwise_core:
    git:
      url: https://github.com/abassimaj123/calcwise_core.git
      ref: main
  image: ^4.1.0



