const fs = require('fs');

const privacyEN = {
  meta: { title: 'Privacy Policy | CalcWise', desc: 'CalcWise privacy policy — website and Android apps. GDPR and CCPA compliant.' },
  heading: 'Privacy Policy', updated: 'Last updated',
  s1: { title: 'Overview', p1: 'CalcWise ("we", "our", "us") operates calqwise.com and a suite of Android financial calculator apps. This Privacy Policy explains how we collect, use, and protect information when you use our services.', keyFact: 'Key fact', p2: 'All financial calculations run entirely in your browser or on your device. We never transmit your financial inputs (income, home price, debt amounts, etc.) to our servers.' },
  s2: { title: 'Website — Information We Collect', calcTitle: '2.1 Calculator Inputs', calcText: 'We do NOT collect, store, or process any financial data you enter into our calculators. All calculations are performed client-side using JavaScript.', analyticsTitle: '2.2 Usage Data (Google Analytics 4)', analyticsText: 'We use Google Analytics 4 to collect anonymized usage data: pages visited, time on page, browser type, approximate geographic region, and referring websites.', analyticsOptOut: 'GA4 data is processed by Google LLC. You can opt out via the Google Analytics Opt-out Browser Add-on.', adsenseTitle: '2.3 Advertising (Google AdSense)', adsenseText: 'We display ads via Google AdSense. Google may use cookies to serve personalized ads. Manage preferences at adssettings.google.com.', contactTitle: '2.4 Contact Form', contactText: 'If you submit our contact form, your name, email, and message are processed through Formspree, solely to respond to your inquiry.' },
  s3: { title: 'Android Apps — Data Collection', intro: 'Our Android apps use third-party SDKs that may collect data. The following apps are covered by this policy:', admobTitle: '3.1 Advertising (Google AdMob)', admobText: 'Our apps display ads via Google AdMob. AdMob may collect device identifiers, IP address, and usage data. Opt out in Google Settings > Ads on your device.', analyticsTitle: '3.2 Usage Analytics (Firebase Analytics)', analyticsText: 'We use Firebase Analytics to collect anonymized usage data (screens viewed, session duration, device type, country). Data is aggregated and cannot identify you personally.', crashlyticsTitle: '3.3 Crash Reporting (Firebase Crashlytics)', crashlyticsText: 'Firebase Crashlytics automatically collects crash reports including device model, OS version, and stack trace. No personal or financial data is included.', noSale: "We do not sell data collected through our apps to third parties. All third-party SDKs are governed by Google's Privacy Policy." },
  s4: { title: 'Cookies', intro: 'Our website uses the following cookies:', analyticsCookie: 'Analytics cookies', analyticsCookieText: 'Google Analytics tracks page views anonymously. Persist for up to 2 years.', adsCookie: 'Advertising cookies', adsCookieText: 'Google AdSense uses cookies to serve and measure ads. Managed by Google.', functionalCookie: 'Functional cookies', functionalCookieText: 'We store your language preference and calculator settings in localStorage. This data never leaves your device.', control: 'You can control cookies through your browser settings. Blocking cookies may affect analytics and ad functionality.' },
  s5: { title: 'GDPR (European Users)', intro: 'If you are in the EEA, you have the following rights under GDPR:', access: 'Right to access', accessText: 'Request a copy of personal data we hold about you.', erasure: 'Right to erasure', erasureText: 'Request deletion of your personal data.', object: 'Right to object', objectText: 'Object to processing of your data for marketing.', portability: 'Right to portability', portabilityText: 'Receive your data in a structured, machine-readable format.', basis: 'Our legal basis for analytics is legitimate interest. For advertising, we rely on consent where required by law.' },
  s6: { title: 'CCPA (California Users)', text: 'California residents have the right to: know what personal information we collect; request deletion; opt out of the sale of personal information (we do not sell data); and non-discrimination for exercising your rights.', note: "Sharing data with Google for analytics and advertising may constitute a 'sale' under CCPA. To opt out, use Google's opt-out tools or enable the Global Privacy Control (GPC) in your browser." },
  s7: { title: "Children's Privacy", text: 'CalcWise and our apps are not directed to children under 13. We do not knowingly collect personal information from children. Contact us immediately if you believe a child has provided personal information.' },
  s8: { title: 'Third-Party Links', text: 'Our website and apps may link to third-party services (Google Play, App Store, financial websites). We are not responsible for their privacy practices.' },
  s9: { title: 'Changes to This Policy', text: 'We may update this Privacy Policy from time to time. Changes will be posted with an updated date. Continued use of CalcWise after changes constitutes acceptance.' },
  s10: { title: 'Contact Us', text: 'For privacy inquiries, data requests, or concerns, email us at', or: 'or use our', contactPage: 'Contact page' }
};

const privacyFR = {
  meta: { title: 'Politique de confidentialite | CalcWise', desc: 'Politique de confidentialite de CalcWise pour le site et les apps Android. Conforme RGPD et CCPA.' },
  heading: 'Politique de confidentialite', updated: 'Derniere mise a jour',
  s1: { title: 'Apercu', p1: "CalcWise exploite le site calqwise.com et une suite d'applications Android. Cette politique explique comment nous collectons, utilisons et protegeons les informations.", keyFact: 'Fait important', p2: "Tous les calculs financiers s'effectuent dans votre navigateur ou sur votre appareil. Nous ne transmettons jamais vos donnees financieres a nos serveurs." },
  s2: { title: 'Site web - Informations collectees', calcTitle: '2.1 Donnees des calculateurs', calcText: 'Nous ne collectons, ne stockons ni ne traitons aucune donnee financiere saisie dans nos calculateurs. Tous les calculs sont effectues cote client.', analyticsTitle: "2.2 Donnees d'utilisation (Google Analytics 4)", analyticsText: 'Nous utilisons Google Analytics 4 pour des donnees anonymisees : pages visitees, duree de session, type de navigateur, region geographique et sites referents.', analyticsOptOut: 'Les donnees GA4 sont traitees par Google LLC. Desactivez via le module complementaire de desinscription Google Analytics.', adsenseTitle: '2.3 Publicite (Google AdSense)', adsenseText: 'Nous affichons des publicites via Google AdSense. Google peut utiliser des cookies pour des annonces personnalisees. Gerez vos preferences sur adssettings.google.com.', contactTitle: '2.4 Formulaire de contact', contactText: 'Si vous soumettez notre formulaire, votre nom, e-mail et message sont traites via Formspree uniquement pour repondre a votre demande.' },
  s3: { title: 'Applications Android - Collecte de donnees', intro: 'Nos applications Android utilisent des SDK tiers pouvant collecter des donnees. Les applications suivantes sont couvertes par cette politique :', admobTitle: '3.1 Publicite (Google AdMob)', admobText: "Nos apps affichent des publicites via Google AdMob. AdMob peut collecter des identifiants d'appareil, l'adresse IP et des donnees d'utilisation. Desactivez dans Parametres Google > Annonces.", analyticsTitle: "3.2 Analyse d'utilisation (Firebase Analytics)", analyticsText: "Nous utilisons Firebase Analytics pour des donnees anonymisees (ecrans consultes, duree de session, type d'appareil, pays). Ces donnees ne permettent pas de vous identifier.", crashlyticsTitle: '3.3 Rapports de plantage (Firebase Crashlytics)', crashlyticsText: "Firebase Crashlytics collecte des rapports de plantage incluant le modele d'appareil, la version d'OS et la trace de debogage. Aucune donnee personnelle n'est incluse.", noSale: 'Nous ne vendons pas les donnees collectees via nos applications. Tous les SDK tiers sont regis par la politique de confidentialite de Google.' },
  s4: { title: 'Cookies', intro: 'Notre site web utilise les cookies suivants :', analyticsCookie: 'Cookies analytiques', analyticsCookieText: "Google Analytics suit les pages visitees anonymement. Duree jusqu'a 2 ans.", adsCookie: 'Cookies publicitaires', adsCookieText: 'Google AdSense utilise des cookies pour diffuser et mesurer les publicites.', functionalCookie: 'Cookies fonctionnels', functionalCookieText: 'Nous stockons vos preferences dans localStorage. Ces donnees ne quittent jamais votre appareil.', control: 'Vous pouvez controler les cookies via les parametres de votre navigateur.' },
  s5: { title: 'RGPD (Utilisateurs europeens)', intro: "Si vous etes dans l'Espace economique europeen, vous disposez des droits suivants :", access: "Droit d'acces", accessText: 'Demander une copie des donnees personnelles que nous detenons sur vous.', erasure: "Droit a l'effacement", erasureText: 'Demander la suppression de vos donnees personnelles.', object: "Droit d'opposition", objectText: 'Vous opposer au traitement de vos donnees a des fins marketing.', portability: 'Droit a la portabilite', portabilityText: 'Recevoir vos donnees dans un format structure et lisible par machine.', basis: "Notre base legale pour l'analytique est l'interet legitime. Pour la publicite, nous nous appuyons sur le consentement." },
  s6: { title: 'CCPA (Utilisateurs californiens)', text: 'Les residents californiens ont le droit de : savoir quelles donnees nous collectons ; demander leur suppression ; refuser la vente de donnees (nous ne vendons pas de donnees) ; et ne pas subir de discrimination.', note: 'Le partage de donnees avec Google peut constituer une vente au sens du CCPA. Utilisez les outils de desinscription de Google ou activez le signal Global Privacy Control (GPC).' },
  s7: { title: 'Protection des mineurs', text: "CalcWise et nos applications ne sont pas destines aux enfants de moins de 13 ans. Nous ne collectons pas sciemment de donnees aupres d'enfants. Contactez-nous immediatement si necessaire." },
  s8: { title: 'Liens tiers', text: "Notre site et nos applications peuvent contenir des liens vers des services tiers. Nous ne sommes pas responsables de leurs pratiques de confidentialite." },
  s9: { title: 'Modifications de cette politique', text: "Nous pouvons mettre a jour cette politique. Les modifications seront publiees avec une date mise a jour. L'utilisation continue de CalcWise vaut acceptation." },
  s10: { title: 'Nous contacter', text: 'Pour toute question relative a la confidentialite, ecrivez-nous a', or: 'ou utilisez notre', contactPage: 'page de contact' }
};

const privacyES = {
  meta: { title: 'Politica de privacidad | CalcWise', desc: 'Politica de privacidad de CalcWise para el sitio web y apps Android. Cumplimiento GDPR y CCPA.' },
  heading: 'Politica de privacidad', updated: 'Ultima actualizacion',
  s1: { title: 'Descripcion general', p1: 'CalcWise opera el sitio calqwise.com y una suite de aplicaciones Android. Esta politica explica como recopilamos, usamos y protegemos la informacion.', keyFact: 'Dato clave', p2: 'Todos los calculos financieros se ejecutan en su navegador o dispositivo. Nunca transmitimos sus datos financieros a nuestros servidores.' },
  s2: { title: 'Sitio web - Informacion recopilada', calcTitle: '2.1 Datos de calculadoras', calcText: 'NO recopilamos, almacenamos ni procesamos ningun dato financiero. Todos los calculos se realizan en el lado del cliente.', analyticsTitle: '2.2 Datos de uso (Google Analytics 4)', analyticsText: 'Usamos Google Analytics 4 para datos anonimos: paginas visitadas, duracion de sesion, tipo de navegador, region y sitios de referencia.', analyticsOptOut: 'Los datos de GA4 son procesados por Google LLC. Desactivelo mediante el complemento de exclusion de Google Analytics.', adsenseTitle: '2.3 Publicidad (Google AdSense)', adsenseText: 'Mostramos anuncios mediante Google AdSense. Google puede usar cookies para anuncios personalizados. Gestione preferencias en adssettings.google.com.', contactTitle: '2.4 Formulario de contacto', contactText: 'Si envia nuestro formulario, su nombre, correo y mensaje son procesados por Formspree para responder su consulta.' },
  s3: { title: 'Aplicaciones Android - Recopilacion de datos', intro: 'Nuestras apps Android utilizan SDKs de terceros que pueden recopilar datos. Las siguientes aplicaciones estan cubiertas:', admobTitle: '3.1 Publicidad (Google AdMob)', admobText: 'Nuestras apps muestran anuncios mediante Google AdMob. AdMob puede recopilar identificadores de dispositivo e IP. Desactive en Configuracion de Google > Anuncios.', analyticsTitle: '3.2 Analisis de uso (Firebase Analytics)', analyticsText: 'Usamos Firebase Analytics para datos anonimos (pantallas, sesion, dispositivo, pais). Los datos son agregados y no permiten identificarle.', crashlyticsTitle: '3.3 Informes de fallos (Firebase Crashlytics)', crashlyticsText: 'Firebase Crashlytics recopila informes de fallos con modelo de dispositivo, version SO y traza de error. No se incluyen datos personales.', noSale: 'No vendemos datos recopilados a traves de nuestras apps. Todos los SDKs se rigen por la politica de privacidad de Google.' },
  s4: { title: 'Cookies', intro: 'Nuestro sitio web usa las siguientes cookies:', analyticsCookie: 'Cookies analiticas', analyticsCookieText: 'Google Analytics rastrea paginas de forma anonima. Persisten hasta 2 anos.', adsCookie: 'Cookies publicitarias', adsCookieText: 'Google AdSense usa cookies para mostrar y medir anuncios.', functionalCookie: 'Cookies funcionales', functionalCookieText: 'Guardamos preferencias en localStorage. Estos datos no abandonan su dispositivo.', control: 'Puede controlar las cookies en la configuracion de su navegador.' },
  s5: { title: 'GDPR (Usuarios europeos)', intro: 'Si esta en el EEE, tiene los siguientes derechos:', access: 'Derecho de acceso', accessText: 'Solicitar copia de los datos que tenemos sobre usted.', erasure: 'Derecho de supresion', erasureText: 'Solicitar la eliminacion de sus datos personales.', object: 'Derecho de oposicion', objectText: 'Oponerse al tratamiento de sus datos con fines de marketing.', portability: 'Derecho de portabilidad', portabilityText: 'Recibir sus datos en formato estructurado y legible por maquina.', basis: 'Nuestra base legal para analisis es el interes legitimo. Para publicidad, nos basamos en el consentimiento.' },
  s6: { title: 'CCPA (Usuarios de California)', text: 'Los residentes de California tienen derecho a: saber que datos recopilamos; solicitar su eliminacion; rechazar la venta de datos (no vendemos datos); y no sufrir discriminacion.', note: 'Compartir datos con Google puede constituir una venta bajo el CCPA. Use las herramientas de exclusion de Google o active el Global Privacy Control (GPC).' },
  s7: { title: 'Privacidad de menores', text: 'CalcWise y nuestras apps no estan dirigidos a menores de 13 anos. No recopilamos datos de menores. Contactenos de inmediato si cree que un menor ha proporcionado informacion.' },
  s8: { title: 'Enlaces de terceros', text: 'Nuestro sitio y apps pueden enlazar a servicios de terceros. No somos responsables de sus practicas de privacidad.' },
  s9: { title: 'Cambios en esta politica', text: 'Podemos actualizar esta politica. Los cambios se publicaran con fecha actualizada. El uso continuado de CalcWise constituye aceptacion.' },
  s10: { title: 'Contactenos', text: 'Para consultas de privacidad, escribanos a', or: 'o use nuestra', contactPage: 'pagina de contacto' }
};

const map = { en: privacyEN, fr: privacyFR, es: privacyES };
Object.entries(map).forEach(([lang, privacy]) => {
  const path = 'D:/web/calcwise/src/i18n/locales/' + lang + '/translation.json';
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  data.privacy = privacy;
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('OK ' + lang);
});
